services:
  - type: web
    name: poker_texas_holdem
    env: java
    buildCommand: chmod +x mvnw && ./mvnw clean install
    startCommand: java -jar target/texas_holdem-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render/java
